### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by atherdon** [dhritimanG/mosh_udemy_course#1]
.

**Comment by dhritimanG** [comment]
Hi Arthur,
Thanks for reaching out to me with this unique opportunity. Your work indeed excites me and I'd love to be a part of and contribute to your ongoing projects and it will also be a great learning experience for me too. Looking forward to hearing back from you.

Have a great weekend, Cheers !!
Dhritiman
________________________________

**Comment by atherdon** [comment]
Hi Dhritiman, I'm glad to know that you're interested.
feel free to ask me your questions

Thanks,
Arthur


On 14-Jul-2018 at 04:42 AM, Dhritiman Ganguly wrote:


Hi Arthur,
Thanks for reaching out to me with this unique opportunity. Your work
indeed excites me and I'd love to be a part of and contribute to your
ongoing projects and it will also be a great learning experience for me
too. Looking forward to hearing back from you.

Have a great weekend, Cheers !!
Dhritiman
________________________________

**Comment by dhritimanG** [comment]
Hi Arthur, thanks for getting back to me. This is the first time I am working on an open source project like this and it greatly excites me! It’d be great if you can tell me the kinds of projects the team is currently working on and what the tentative time of development is for them and also a bit about your product GroceriStar so that I can get a better understanding about it.

Thanks,
Dhritiman

________________________________
